### ISSUE TITLE
Malformed ePUB Still

### ISSUE THREAD

**Issue by LadyAsh963** [waylaidwanderer/FicSave#83]
Formerly issue #77, the ePUBs are still not working for story #7069595, and I found the same problem with #5084287 and #3230439, all on FFN. When downloaded as MOBI, and converted to ePub using Calibre, the file functions.

**Comment by waylaidwanderer** [comment]
I just tried downloading Dawns of Yesterday and the ePub came out fine. What issue are you having?

**Comment by LadyAsh963** [comment]
When I upload the files to google books, it can't read them. Google in their help section provides a ![ePUB file validator](http://validator.idpf.org/) the ![list](https://cloud.githubusercontent.com/assets/13737785/9291032/1801e586-435f-11e5-89b0-296a0fdc8f94.PNG) is longer than what is shown here but may give you an idea

**Comment by waylaidwanderer** [comment]
Fixed the issue by stripping attributes from HTML tags and adding `type` attributes to `style` tags. Thanks for the report!

![we3jsdv](https://cloud.githubusercontent.com/assets/2882110/9291254/eba12708-4369-11e5-886e-8d004a9652fc.png)

**Comment by LadyAsh963** [comment]
Dawns of Yesterday is working for me now too, however "thank you ms. bones" #3230439 still isn't validating correctly.
![capture](https://cloud.githubusercontent.com/assets/13737785/9291292/dc17092c-436b-11e5-8ae2-022d31d2ee4e.PNG)

**Comment by waylaidwanderer** [comment]
I've fixed the code causing the issue and the fanfic validates properly now. Let me know if you find anymore fanfics causing issues. Thanks!
